config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'pages#top'

  resources :users
  resources :boards
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :user_id, presence: true
  validates :tittle, presence: true
  validates :deadline, presence: true
  
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  validates :user_id, presence: true
  validates :tittle, presence: true
  validates :content, presence: true
  validates :term, presence: true
  validates :staff, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  #validates :department, presence: true
  #validates :division, presence: true
  #validates :section, presence: true
  #validates :Position, presence: true
  validates :name, presence: true
  #validates :tel, presence: true
  validates :email, presence: true

  has_secure_password
  
  has_many :boards
end

app/models/user_project.rb
class UserProject < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url , info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    #binding.pry
    if @user.save
      redirect_to root_path, success: '登録成功'
    else
      flash.now[:danger] = "登録失敗"
      render :new
    end
  end
  
  private
def user_params
  params.require(:user).permit(:name , :email, :password , :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @boards.each do |board| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
            </h2>
            <%= board.tittle %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= board.deadline %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/boards/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Project</h1>
        <%= form_for @board do |f| %>
          <div class="form-group">
            <%= f.label :tittle %>
            <%= f.text_area :tittle, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :deadline %>
            <%= f.text_area :deadline, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartjob</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <script>
      $(function(){
      $(".alert").fadeOut(5000);
      });
    </script>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to "#" do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_board_path do %>
                <%= image_tag "icons/board.jpg" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/pages/top.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Smart Job Top Page</h1>
    <h2 class="text-white">Smart Job Top Page.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', login_path,class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @projects.each do |project| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
            </h2>
            <%= project.title %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= board.staff %>
            </p>
            <p class="topic-text">
              <%= board.term %>
            </p>
            <p class="topic-text">
              <%= board.content %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Project</h1>
        <%= form_for @project do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_area :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :term %>
            <%= f.text_area :team, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :staff %>
            <%= f.text_area :staff, class: 'form-control' %>
          </div>
          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
        <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>